---
#- name: install git
#  package:
#    name: git 
#    state: present
#
#- name: "[Dariah-Repo] Download the code in the shared data aerea"
#  run_once: true
#  git:
#    repo: 'https://github.com/indigo-dc/dariah-repository.git'
#    dest: /data/zenodo

- name: Register nslookup marathon.service.consul result
  command: nslookup marathon.service.consul
  register: ns

- set_fact: marathon_host=marathon.service.consul

- set_fact: marathon_host=localhost
  when: "'server can\\'t find' in ns.stdout"

- name: "[Dariah-Repo] Prepare repository data root"
  run_once: true
  file:
    path: /data/zenodo-data
    state: directory
    mode: 0777

- name: "[Dariah-Repo] Check if the group is already present"
  run_once: true
  uri: 
     url: "{{marathon_protocol}}://{{marathon_host}}:{{marathon_port}}/v2/groups/dariah"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: GET
     status_code: 200, 404
  register: get_result
  until: get_result | success
  retries: 5
  delay: 20 
  tags:
    - dariah


- name: debug
  debug: var=get_result
  tags:
    - dariah

- name: debug
  debug: msg="{{ lookup('template', 'templates/group.json') }}"
  tags:
   - dariah
  

- name: "[Dariah-Repo] deploy containers on Marathon"
  run_once: true
  uri: 
     url: "{{marathon_protocol}}://{{marathon_host}}:{{marathon_port}}/v2/groups"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: POST
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/group.json') }}"
     body_format: json
     status_code: 201
  register: post_result
  when: get_result.status == 404
  until: post_result | success
  retries: 5
  delay: 20
  tags:
    - dariah


- name: debug
  debug: var=post_result
  tags:
    - dariah

- name: "[Dariah-Repo] Update the Marathon group if already present"
  run_once: true
  uri:
     url: "{{marathon_protocol}}://{{marathon_host}}:{{marathon_port}}/v2/groups"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/group.json') }}"
     body_format: json
     status_code: 200
  register: put_result
  when: get_result.status == 200
  until: put_result | success
  retries: 5
  delay: 20
  tags:
    - dariah

- name: debug
  debug: var=put_result
  tags:
    - dariah


